"""Configuration for Rust toolchains and dependencies.

This module sets up the Rust toolchain, LLVM toolchain, and required crates
for Rust service development.
"""

sysroot = use_repo_rule("@toolchains_llvm//toolchain:sysroot.bzl", "sysroot")

# INTEL/AMD64 Sysroot.
sysroot(
    name = "sysroot_linux_amd64",
    sha256 = "227ce21d631774420046065dee4080c001a9e09e6ef01bb4a5e9d73a6701fe41",
    urls = ["https://github.com/amsokol/cross-compilation-sysroots/releases/download/2026-04-24/debian-trixie-sysroot-amd64.tar.xz"],
)

# ARM 64 Sysroot.
sysroot(
    name = "sysroot_linux_arm64",
    sha256 = "61578c90b6230dc3ade24a08a7961f6a967f56aea0568d044b35ca245eec7941",
    urls = ["https://github.com/amsokol/cross-compilation-sysroots/releases/download/2026-04-24/debian-trixie-sysroot-arm64.tar.xz"],
)

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm", dev_dependency = True)
llvm.toolchain(
    name = "llvm_toolchain",
    extra_llvm_distributions = {
        "LLVM-22.1.4-Linux-ARM64.tar.xz": "ac8bed48a6481ccc0e14af18f64d44fc1ca8c0ccf630c1d4dc5e97027e87e6fa",
        "LLVM-22.1.4-Linux-X64.tar.xz": "cdf232e3bc5d9909ddcf8cb7016802c6745a01e69a596747c684caa894a11567",
        "LLVM-22.1.4-macOS-ARM64.tar.xz": "45e0dfc0453624caed5e7b20e224ce8343af9c511c7f59803753a586620d6ad1",
    },
    llvm_version = "22.1.4",
)
llvm.sysroot(
    name = "llvm_toolchain",
    label = "@sysroot_linux_amd64//sysroot:sysroot",
    targets = ["linux-x86_64"],
)
llvm.sysroot(
    name = "llvm_toolchain",
    label = "@sysroot_linux_arm64//sysroot:sysroot",
    targets = ["linux-aarch64"],
)
use_repo(llvm, "llvm_toolchain")

register_toolchains(
    "@llvm_toolchain//:all",
    dev_dependency = True,
)

RUST_EDITION = "2024"

RUST_VERSION = "1.95.0"

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = RUST_EDITION,
    extra_target_triples = [
        "aarch64-unknown-linux-gnu",
        "x86_64-unknown-linux-gnu",
    ],
    versions = [RUST_VERSION],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

cargo = use_extension(
    "@rules_rust//crate_universe:extensions.bzl",
    "crate",
)
cargo.from_cargo(
    name = "cargo",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
    ],
)
use_repo(cargo, "cargo")
